fix(all): Allow hmr to work on global_defs.rb (#1156)
The `hmr.rb` fix addresses this step 1.
```
--- Lich: error: client_thread: undefined method 'include?' for an instance of NameError                                                                                                                             
/home/mahtra/lich/lib/common/hmr.rb:10:in 'Lich::Common::HMR.msg'
```
Which reveals
```
>;hmr global_defs.rb                                                                                                                                                                                                 
undefined method 'abort' for class 'Object'                                                                                                                                                                          
/home/mahtra/lich/lib/global_defs.rb:2538:in '<top (required)>'                                                                                                                                                      
/home/mahtra/lich/lib/common/hmr.rb:25:in 'Kernel#load'                                                                                                                                                              
/home/mahtra/lich/lib/common/hmr.rb:25:in 'block in Lich::Common::HMR.reload'                                                                                                                                        
/home/mahtra/lich/lib/common/hmr.rb:23:in 'Array#each'                                                                                                                                                               
/home/mahtra/lich/lib/common/hmr.rb:23:in 'Lich::Common::HMR.reload'                                                                                                                                                 
/home/mahtra/lich/lib/global_defs.rb:2284:in 'Object#do_client'                                                                                                                                                      
/home/mahtra/lich/lib/main/main.rb:718:in 'block (3 levels) in <top (required)>'                                                                                                                                     
<internal:kernel>:168:in 'Kernel#loop'                                                                                                                                                                               
/home/mahtra/lich/lib/main/main.rb:649:in 'block (2 levels) in <top (required)>'
```
And with this PR it actually works.
<!-- ELLIPSIS_HIDDEN -->

----

> [!IMPORTANT]
> Fixes error handling in `hmr.rb` and ensures `hmr` command works on
`global_defs.rb` by checking method existence before undefining.
> 
>   - **Behavior**:
> - Fixes error handling in `Lich::Common::HMR.reload` in `hmr.rb` by
changing `self.msg exception` to `self.msg exception.message` to
correctly display error messages.
> - Allows `hmr` command to work on `global_defs.rb` by modifying `undef
:abort` to `undef :abort if respond_to?(:abort)` in `global_defs.rb` to
prevent errors if `abort` is not defined.
> 
> <sup>This description was created by </sup>[<img alt="Ellipsis"
src="https://img.shields.io/badge/Ellipsis-blue?color=175173">](https://www.ellipsis.dev?ref=elanthia-online%2Flich-5&utm_source=github&utm_medium=referral)<sup>
for 299c6e194638682b13d7b9e6ef2b7ad5458a4404. You can
[customize](https://app.ellipsis.dev/elanthia-online/settings/summaries)
this summary. It will automatically update as commits are pushed.</sup>

<!-- ELLIPSIS_HIDDEN -->